version: '3'
services:
    timesheets:
        #container 1 - timesheets
        container_name: timesheet_container
        restart: always
        build: . #build from local dockerfile
        env_file: ./.env
        ports:
            - ${TIMESHEET_PORTS_MAPPING}
        depends_on:
            - mongodb
            - mysqldb
    mongodb:
        #container 2 - mondodb
        container_name: mongodb_container
        image: mongo:latest
        ports:
            - ${MONGO_PORTS_MAPPING}
        volumes:
            - "${MONGO_VOLUME}"
        restart: unless-stopped
    mysqldb:
        image: mysql:5.7
        env_file: ./.env
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${MY_SQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MY_SQL_DATABASE}
        ports:
            - ${MY_SQL_PORT}
        volumes:
            - ${MY_SQL_VOLUME}
