version: '3'
services:
    timesheets:
        #container 1 - timesheets
        container_name: timesheet_container
        restart: always
        build: . #build from local dockerfile
        env_file: ./.env
        ports:
            - ${TIMESHEET_PORTS_MAPPING}
        depends_on:
            - mongodb
            - mysqldb
    mongodb:
        #container 2 - mondodb
        container_name: mongodb
        image: mongo:latest
        ports:
            - ${MONGO_PORTS_MAPPING}
        expose:
            - ${MONGO_PORT}
        volumes:
            - "${MONGO_VOLUME}"
        restart: unless-stopped
    mysqldb: 
        #container 3 - mysql
        container_name: mysqldb_container
        image: mysql:latest
        env_file: ./.env
        restart: unless-stopped
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: ${MY_SQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MY_SQL_DATABASE}
        expose:
            - ${MY_SQL_PORT}
        ports:
            - ${MY_SQL_PORTS_MAPPING}
        volumes:
            - ${MY_SQL_VOLUME}
